version: "3.1"
services:

  bank_ocr_nginx:
    image: nginx:alpine
    ports:
      - "9080:80"
    depends_on:
      - bank_ocr_php
    volumes:
      - ./docker/nginx/bank_ocr.conf:/etc/nginx/conf.d/default.conf:cached
    container_name: bank_ocr_nginx

  bank_ocr_php:
    build:
      context: ./
    volumes:
      - .:/application
    container_name: bank_ocr_php
