version: "3.1"
services:

  bank_ocr_nginx:
    image: nginx:alpine
    ports:
      - "9080:80"
      - "9443:443"
    depends_on:
      - bank_ocr_php
    volumes:
      - docker_bank_ocr_nfsmount:/bankOCR:delegated
      - ./nginx/bank_ocr.conf:/etc/nginx/conf.d/default.conf:cached
    container_name: bank_ocr_nginx

  bank_ocr_php:
    build: php/
    volumes:
      - docker_bank_ocr_nfsmount:/bankOCR:delegated
    container_name: bank_ocr_php
volumes:
  docker_bank_ocr_nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: /bankOCR:/Users/$USER/Sites/bankOcr
